{% set name = "wheel-filename" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wheel-filename-{{ version }}.tar.gz
  sha256: e2e1eb0780910a0148358252aad6394cc674250686c56c39aa379493438370b3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - wheel-filename = wheel_filename.__main__:main

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - wheel_filename
  commands:
    - pip check
    - wheel-filename --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jwodder/wheel-filename
  summary: Parse wheel filenames
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beenje
