{% set name = "wheel-filename" %}
{% set version = "1.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 87891c465dcbb40b40394a906f01a93214bdd51aa5d25e3a9a59cae62bc298fd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - wheel-filename = wheel_filename.__main__:main

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - wheel_filename
  commands:
    - pip check
    - wheel-filename --help
  requires:
    - pip

about:
  home: https://github.com/jwodder/wheel-filename
  summary: Parse wheel filenames
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beenje
