schema_version: 1

context:
  name: wheel-filename
  version: "2.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 6c0d74ed6f43ad17905233a920ded245e965a874506f5d8c5882fb848c7b0f83

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - wheel-filename = wheel_filename.__main__:main

requirements:
  host:
    - pip
    - hatchling
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - wheel_filename
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check
      - wheel-filename --help

about:
  summary: Parse wheel filenames
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/wheelodex/wheel-filename

extra:
  recipe-maintainers:
    - beenje
